[package]
name = "vbus2influx"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.5"
figment = { version = "0.10.19", features = ["toml"] }
resol-vbus = "0.2.1"
rppal = "0.22.1"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
axum = "0.8.9"
influxdb2 = "0.5.2"
futures = "0.3"

[profile.release]
strip = true
